//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace MvcMobile.PermissionService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PermissionServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PermissionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPermissionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPermissionPagingOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePermissionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPermissionsByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPermissionByRoleIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsExistPermissionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PermissionService() {
            this.Url = global::MvcMobile.Properties.Settings.Default.MvcMobile_PermissionService_PermissionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPermissionCompletedEventHandler GetPermissionCompleted;
        
        /// <remarks/>
        public event GetPermissionsCompletedEventHandler GetPermissionsCompleted;
        
        /// <remarks/>
        public event GetPermissionPagingCompletedEventHandler GetPermissionPagingCompleted;
        
        /// <remarks/>
        public event AddPermissionCompletedEventHandler AddPermissionCompleted;
        
        /// <remarks/>
        public event DeletePermissionCompletedEventHandler DeletePermissionCompleted;
        
        /// <remarks/>
        public event UpdatePermissionCompletedEventHandler UpdatePermissionCompleted;
        
        /// <remarks/>
        public event GetPermissionsByUserIdCompletedEventHandler GetPermissionsByUserIdCompleted;
        
        /// <remarks/>
        public event GetPermissionByRoleIdCompletedEventHandler GetPermissionByRoleIdCompleted;
        
        /// <remarks/>
        public event IsExistPermissionCompletedEventHandler IsExistPermissionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SystemPermission GetPermission(int permissionId) {
            object[] results = this.Invoke("GetPermission", new object[] {
                        permissionId});
            return ((SystemPermission)(results[0]));
        }
        
        /// <remarks/>
        public void GetPermissionAsync(int permissionId) {
            this.GetPermissionAsync(permissionId, null);
        }
        
        /// <remarks/>
        public void GetPermissionAsync(int permissionId, object userState) {
            if ((this.GetPermissionOperationCompleted == null)) {
                this.GetPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPermissionOperationCompleted);
            }
            this.InvokeAsync("GetPermission", new object[] {
                        permissionId}, this.GetPermissionOperationCompleted, userState);
        }
        
        private void OnGetPermissionOperationCompleted(object arg) {
            if ((this.GetPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPermissionCompleted(this, new GetPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPermissions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SystemPermission[] GetPermissions(int companyId, string keyword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> isDeleted) {
            object[] results = this.Invoke("GetPermissions", new object[] {
                        companyId,
                        keyword,
                        isDeleted});
            return ((SystemPermission[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPermissionsAsync(int companyId, string keyword, System.Nullable<bool> isDeleted) {
            this.GetPermissionsAsync(companyId, keyword, isDeleted, null);
        }
        
        /// <remarks/>
        public void GetPermissionsAsync(int companyId, string keyword, System.Nullable<bool> isDeleted, object userState) {
            if ((this.GetPermissionsOperationCompleted == null)) {
                this.GetPermissionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPermissionsOperationCompleted);
            }
            this.InvokeAsync("GetPermissions", new object[] {
                        companyId,
                        keyword,
                        isDeleted}, this.GetPermissionsOperationCompleted, userState);
        }
        
        private void OnGetPermissionsOperationCompleted(object arg) {
            if ((this.GetPermissionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPermissionsCompleted(this, new GetPermissionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPermissionPaging", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PagedResultOfSystemPermission GetPermissionPaging(int companyId, string keyword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> isDeleted, PagingInput pagingInput) {
            object[] results = this.Invoke("GetPermissionPaging", new object[] {
                        companyId,
                        keyword,
                        isDeleted,
                        pagingInput});
            return ((PagedResultOfSystemPermission)(results[0]));
        }
        
        /// <remarks/>
        public void GetPermissionPagingAsync(int companyId, string keyword, System.Nullable<bool> isDeleted, PagingInput pagingInput) {
            this.GetPermissionPagingAsync(companyId, keyword, isDeleted, pagingInput, null);
        }
        
        /// <remarks/>
        public void GetPermissionPagingAsync(int companyId, string keyword, System.Nullable<bool> isDeleted, PagingInput pagingInput, object userState) {
            if ((this.GetPermissionPagingOperationCompleted == null)) {
                this.GetPermissionPagingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPermissionPagingOperationCompleted);
            }
            this.InvokeAsync("GetPermissionPaging", new object[] {
                        companyId,
                        keyword,
                        isDeleted,
                        pagingInput}, this.GetPermissionPagingOperationCompleted, userState);
        }
        
        private void OnGetPermissionPagingOperationCompleted(object arg) {
            if ((this.GetPermissionPagingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPermissionPagingCompleted(this, new GetPermissionPagingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddPermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddPermission(SystemPermission objPermission) {
            object[] results = this.Invoke("AddPermission", new object[] {
                        objPermission});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddPermissionAsync(SystemPermission objPermission) {
            this.AddPermissionAsync(objPermission, null);
        }
        
        /// <remarks/>
        public void AddPermissionAsync(SystemPermission objPermission, object userState) {
            if ((this.AddPermissionOperationCompleted == null)) {
                this.AddPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPermissionOperationCompleted);
            }
            this.InvokeAsync("AddPermission", new object[] {
                        objPermission}, this.AddPermissionOperationCompleted, userState);
        }
        
        private void OnAddPermissionOperationCompleted(object arg) {
            if ((this.AddPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPermissionCompleted(this, new AddPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletePermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeletePermission(int permissionId, int userId) {
            object[] results = this.Invoke("DeletePermission", new object[] {
                        permissionId,
                        userId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePermissionAsync(int permissionId, int userId) {
            this.DeletePermissionAsync(permissionId, userId, null);
        }
        
        /// <remarks/>
        public void DeletePermissionAsync(int permissionId, int userId, object userState) {
            if ((this.DeletePermissionOperationCompleted == null)) {
                this.DeletePermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePermissionOperationCompleted);
            }
            this.InvokeAsync("DeletePermission", new object[] {
                        permissionId,
                        userId}, this.DeletePermissionOperationCompleted, userState);
        }
        
        private void OnDeletePermissionOperationCompleted(object arg) {
            if ((this.DeletePermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePermissionCompleted(this, new DeletePermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePermission(SystemPermission objPermission) {
            object[] results = this.Invoke("UpdatePermission", new object[] {
                        objPermission});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePermissionAsync(SystemPermission objPermission) {
            this.UpdatePermissionAsync(objPermission, null);
        }
        
        /// <remarks/>
        public void UpdatePermissionAsync(SystemPermission objPermission, object userState) {
            if ((this.UpdatePermissionOperationCompleted == null)) {
                this.UpdatePermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePermissionOperationCompleted);
            }
            this.InvokeAsync("UpdatePermission", new object[] {
                        objPermission}, this.UpdatePermissionOperationCompleted, userState);
        }
        
        private void OnUpdatePermissionOperationCompleted(object arg) {
            if ((this.UpdatePermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePermissionCompleted(this, new UpdatePermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPermissionsByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetPermissionsByUserId(int userId) {
            object[] results = this.Invoke("GetPermissionsByUserId", new object[] {
                        userId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPermissionsByUserIdAsync(int userId) {
            this.GetPermissionsByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetPermissionsByUserIdAsync(int userId, object userState) {
            if ((this.GetPermissionsByUserIdOperationCompleted == null)) {
                this.GetPermissionsByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPermissionsByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetPermissionsByUserId", new object[] {
                        userId}, this.GetPermissionsByUserIdOperationCompleted, userState);
        }
        
        private void OnGetPermissionsByUserIdOperationCompleted(object arg) {
            if ((this.GetPermissionsByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPermissionsByUserIdCompleted(this, new GetPermissionsByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPermissionByRoleId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SystemPermission[] GetPermissionByRoleId(int roleId) {
            object[] results = this.Invoke("GetPermissionByRoleId", new object[] {
                        roleId});
            return ((SystemPermission[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPermissionByRoleIdAsync(int roleId) {
            this.GetPermissionByRoleIdAsync(roleId, null);
        }
        
        /// <remarks/>
        public void GetPermissionByRoleIdAsync(int roleId, object userState) {
            if ((this.GetPermissionByRoleIdOperationCompleted == null)) {
                this.GetPermissionByRoleIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPermissionByRoleIdOperationCompleted);
            }
            this.InvokeAsync("GetPermissionByRoleId", new object[] {
                        roleId}, this.GetPermissionByRoleIdOperationCompleted, userState);
        }
        
        private void OnGetPermissionByRoleIdOperationCompleted(object arg) {
            if ((this.GetPermissionByRoleIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPermissionByRoleIdCompleted(this, new GetPermissionByRoleIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsExistPermission", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsExistPermission(int permissionId) {
            object[] results = this.Invoke("IsExistPermission", new object[] {
                        permissionId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsExistPermissionAsync(int permissionId) {
            this.IsExistPermissionAsync(permissionId, null);
        }
        
        /// <remarks/>
        public void IsExistPermissionAsync(int permissionId, object userState) {
            if ((this.IsExistPermissionOperationCompleted == null)) {
                this.IsExistPermissionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsExistPermissionOperationCompleted);
            }
            this.InvokeAsync("IsExistPermission", new object[] {
                        permissionId}, this.IsExistPermissionOperationCompleted, userState);
        }
        
        private void OnIsExistPermissionOperationCompleted(object arg) {
            if ((this.IsExistPermissionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsExistPermissionCompleted(this, new IsExistPermissionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemPermission {
        
        private int permissionIDField;
        
        private string permissionNameField;
        
        private int createdByField;
        
        private System.DateTime createdDateField;
        
        private bool isDeletedField;
        
        private System.Nullable<int> deletedByField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private System.Nullable<int> companyIDField;
        
        private SystemRolePermission[] systemRolePermissionsField;
        
        /// <remarks/>
        public int PermissionID {
            get {
                return this.permissionIDField;
            }
            set {
                this.permissionIDField = value;
            }
        }
        
        /// <remarks/>
        public string PermissionName {
            get {
                return this.permissionNameField;
            }
            set {
                this.permissionNameField = value;
            }
        }
        
        /// <remarks/>
        public int CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public SystemRolePermission[] SystemRolePermissions {
            get {
                return this.systemRolePermissionsField;
            }
            set {
                this.systemRolePermissionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemRolePermission {
        
        private int idField;
        
        private int roleIDField;
        
        private int permissionIDField;
        
        private SystemPermission systemPermissionField;
        
        private SystemRole systemRoleField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public int PermissionID {
            get {
                return this.permissionIDField;
            }
            set {
                this.permissionIDField = value;
            }
        }
        
        /// <remarks/>
        public SystemPermission SystemPermission {
            get {
                return this.systemPermissionField;
            }
            set {
                this.systemPermissionField = value;
            }
        }
        
        /// <remarks/>
        public SystemRole SystemRole {
            get {
                return this.systemRoleField;
            }
            set {
                this.systemRoleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemRole {
        
        private int roleIDField;
        
        private string roleNameField;
        
        private string descriptionField;
        
        private bool isActivedField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<int> createdByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private bool isDeletedField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<int> deletedByField;
        
        private SystemRolePermission[] systemRolePermissionsField;
        
        private SystemRoleUser[] systemRoleUsersField;
        
        /// <remarks/>
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActived {
            get {
                return this.isActivedField;
            }
            set {
                this.isActivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public SystemRolePermission[] SystemRolePermissions {
            get {
                return this.systemRolePermissionsField;
            }
            set {
                this.systemRolePermissionsField = value;
            }
        }
        
        /// <remarks/>
        public SystemRoleUser[] SystemRoleUsers {
            get {
                return this.systemRoleUsersField;
            }
            set {
                this.systemRoleUsersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemRoleUser {
        
        private int idField;
        
        private System.Nullable<int> roleIDField;
        
        private System.Nullable<int> userIDField;
        
        private SystemRole systemRoleField;
        
        private SystemUser systemUserField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public SystemRole SystemRole {
            get {
                return this.systemRoleField;
            }
            set {
                this.systemRoleField = value;
            }
        }
        
        /// <remarks/>
        public SystemUser SystemUser {
            get {
                return this.systemUserField;
            }
            set {
                this.systemUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemUser {
        
        private int userIDField;
        
        private string emailField;
        
        private string passwordField;
        
        private string fullNameField;
        
        private string phoneNumberField;
        
        private string mobiField;
        
        private string addressField;
        
        private string descriptionField;
        
        private string avatarField;
        
        private bool isRequirePwdChangeField;
        
        private bool isLockedField;
        
        private bool isDeletedField;
        
        private System.Nullable<System.DateTime> lastLoginDateField;
        
        private System.Nullable<System.DateTime> lockedDateField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<int> createdByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<int> deletedByField;
        
        private System.Nullable<int> companyIDField;
        
        private System.Nullable<int> invitatedByField;
        
        private Company companyField;
        
        private SystemRoleUser[] systemRoleUsersField;
        
        private SystemUser[] systemUser1Field;
        
        private SystemUser[] systemUsersField;
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Mobi {
            get {
                return this.mobiField;
            }
            set {
                this.mobiField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Avatar {
            get {
                return this.avatarField;
            }
            set {
                this.avatarField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRequirePwdChange {
            get {
                return this.isRequirePwdChangeField;
            }
            set {
                this.isRequirePwdChangeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastLoginDate {
            get {
                return this.lastLoginDateField;
            }
            set {
                this.lastLoginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LockedDate {
            get {
                return this.lockedDateField;
            }
            set {
                this.lockedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InvitatedBy {
            get {
                return this.invitatedByField;
            }
            set {
                this.invitatedByField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public SystemRoleUser[] SystemRoleUsers {
            get {
                return this.systemRoleUsersField;
            }
            set {
                this.systemRoleUsersField = value;
            }
        }
        
        /// <remarks/>
        public SystemUser[] SystemUser1 {
            get {
                return this.systemUser1Field;
            }
            set {
                this.systemUser1Field = value;
            }
        }
        
        /// <remarks/>
        public SystemUser[] SystemUsers {
            get {
                return this.systemUsersField;
            }
            set {
                this.systemUsersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Company {
        
        private int companyIDField;
        
        private System.Nullable<bool> isActivedField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<int> createdByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<int> deletedByField;
        
        private string companyNameField;
        
        private string addressField;
        
        private string telephoneField;
        
        private string taxCodeField;
        
        private string websiteField;
        
        private string emailField;
        
        private bool isDeletedField;
        
        private string companyCodeField;
        
        private string keyField;
        
        private System.Nullable<System.DateTime> expiredDateField;
        
        private System.Nullable<int> parentIDField;
        
        private bool isRootSiteField;
        
        private CompanyOnlineSupport[] companyOnlineSupportsField;
        
        private CompanyProfile companyProfileField;
        
        private Manufacturer[] manufacturersField;
        
        private MediaCategory[] mediaCategoriesField;
        
        private MediaFile[] mediaFilesField;
        
        private SystemCompanyConfig[] systemCompanyConfigsField;
        
        private SystemUser[] systemUsersField;
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActived {
            get {
                return this.isActivedField;
            }
            set {
                this.isActivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpiredDate {
            get {
                return this.expiredDateField;
            }
            set {
                this.expiredDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsRootSite {
            get {
                return this.isRootSiteField;
            }
            set {
                this.isRootSiteField = value;
            }
        }
        
        /// <remarks/>
        public CompanyOnlineSupport[] CompanyOnlineSupports {
            get {
                return this.companyOnlineSupportsField;
            }
            set {
                this.companyOnlineSupportsField = value;
            }
        }
        
        /// <remarks/>
        public CompanyProfile CompanyProfile {
            get {
                return this.companyProfileField;
            }
            set {
                this.companyProfileField = value;
            }
        }
        
        /// <remarks/>
        public Manufacturer[] Manufacturers {
            get {
                return this.manufacturersField;
            }
            set {
                this.manufacturersField = value;
            }
        }
        
        /// <remarks/>
        public MediaCategory[] MediaCategories {
            get {
                return this.mediaCategoriesField;
            }
            set {
                this.mediaCategoriesField = value;
            }
        }
        
        /// <remarks/>
        public MediaFile[] MediaFiles {
            get {
                return this.mediaFilesField;
            }
            set {
                this.mediaFilesField = value;
            }
        }
        
        /// <remarks/>
        public SystemCompanyConfig[] SystemCompanyConfigs {
            get {
                return this.systemCompanyConfigsField;
            }
            set {
                this.systemCompanyConfigsField = value;
            }
        }
        
        /// <remarks/>
        public SystemUser[] SystemUsers {
            get {
                return this.systemUsersField;
            }
            set {
                this.systemUsersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyOnlineSupport {
        
        private long onlineSupportIDField;
        
        private int companyIDField;
        
        private string nickField;
        
        private string displayNameField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<int> createdByField;
        
        private System.Nullable<bool> isDeletedField;
        
        private System.Nullable<bool> isActivedField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<int> deletedByField;
        
        private int onlineSupportTypeIDField;
        
        private int orderIndexField;
        
        private Company companyField;
        
        private OnlineSupportType onlineSupportTypeField;
        
        /// <remarks/>
        public long OnlineSupportID {
            get {
                return this.onlineSupportIDField;
            }
            set {
                this.onlineSupportIDField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string Nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActived {
            get {
                return this.isActivedField;
            }
            set {
                this.isActivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public int OnlineSupportTypeID {
            get {
                return this.onlineSupportTypeIDField;
            }
            set {
                this.onlineSupportTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int OrderIndex {
            get {
                return this.orderIndexField;
            }
            set {
                this.orderIndexField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public OnlineSupportType OnlineSupportType {
            get {
                return this.onlineSupportTypeField;
            }
            set {
                this.onlineSupportTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OnlineSupportType {
        
        private int typeIDField;
        
        private string nameField;
        
        private string patternField;
        
        private System.DateTime createdDateField;
        
        private int createdByField;
        
        private bool isDeletedField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<int> deletedByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private CompanyOnlineSupport[] companyOnlineSupportsField;
        
        /// <remarks/>
        public int TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public int CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        public CompanyOnlineSupport[] CompanyOnlineSupports {
            get {
                return this.companyOnlineSupportsField;
            }
            set {
                this.companyOnlineSupportsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PagedResultOfSystemPermission {
        
        private SystemPermission[] resultsField;
        
        private long rowCountField;
        
        /// <remarks/>
        public SystemPermission[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public long RowCount {
            get {
                return this.rowCountField;
            }
            set {
                this.rowCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PagingInput {
        
        private int pageIndexField;
        
        private int pageSizeField;
        
        private SortDirection sortDirectionField;
        
        private string sortPropertyNameField;
        
        public PagingInput() {
            this.pageSizeField = 10;
        }
        
        /// <remarks/>
        public int PageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                this.pageIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public SortDirection SortDirection {
            get {
                return this.sortDirectionField;
            }
            set {
                this.sortDirectionField = value;
            }
        }
        
        /// <remarks/>
        public string SortPropertyName {
            get {
                return this.sortPropertyNameField;
            }
            set {
                this.sortPropertyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SortDirection {
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SystemCompanyConfig {
        
        private string configIDField;
        
        private int companyIDField;
        
        private string configNameField;
        
        private string configValueField;
        
        private string descriptionField;
        
        private System.DateTime createdDateField;
        
        private int createdByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private Company companyField;
        
        /// <remarks/>
        public string ConfigID {
            get {
                return this.configIDField;
            }
            set {
                this.configIDField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string ConfigName {
            get {
                return this.configNameField;
            }
            set {
                this.configNameField = value;
            }
        }
        
        /// <remarks/>
        public string ConfigValue {
            get {
                return this.configValueField;
            }
            set {
                this.configValueField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public int CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MediaFile {
        
        private long fileIDField;
        
        private int companyIDField;
        
        private string fileUrlField;
        
        private string descriptionField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<int> createdByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<int> deletedByField;
        
        private System.Nullable<bool> isDeletedField;
        
        private int fileTypeIDField;
        
        private int categoryIDField;
        
        private Company companyField;
        
        private MediaCategory mediaCategoryField;
        
        /// <remarks/>
        public long FileID {
            get {
                return this.fileIDField;
            }
            set {
                this.fileIDField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string FileUrl {
            get {
                return this.fileUrlField;
            }
            set {
                this.fileUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public int FileTypeID {
            get {
                return this.fileTypeIDField;
            }
            set {
                this.fileTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public MediaCategory MediaCategory {
            get {
                return this.mediaCategoryField;
            }
            set {
                this.mediaCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MediaCategory {
        
        private int categoryIDField;
        
        private int companyIDField;
        
        private System.Nullable<int> parentCategoryField;
        
        private System.Nullable<int> refCategoryIDField;
        
        private string categoryNameField;
        
        private string categoryName_EnField;
        
        private string descriptionField;
        
        private string description_EnField;
        
        private string imageUrlField;
        
        private int orderIndexField;
        
        private System.Nullable<bool> isActivedField;
        
        private System.Nullable<bool> isDeletedField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private string modifiedByField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private string deletedByField;
        
        private string logNoteField;
        
        private Company companyField;
        
        private MediaFile[] mediaFilesField;
        
        /// <remarks/>
        public int CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ParentCategory {
            get {
                return this.parentCategoryField;
            }
            set {
                this.parentCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RefCategoryID {
            get {
                return this.refCategoryIDField;
            }
            set {
                this.refCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName_En {
            get {
                return this.categoryName_EnField;
            }
            set {
                this.categoryName_EnField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Description_En {
            get {
                return this.description_EnField;
            }
            set {
                this.description_EnField = value;
            }
        }
        
        /// <remarks/>
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        public int OrderIndex {
            get {
                return this.orderIndexField;
            }
            set {
                this.orderIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActived {
            get {
                return this.isActivedField;
            }
            set {
                this.isActivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        public string ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public string LogNote {
            get {
                return this.logNoteField;
            }
            set {
                this.logNoteField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public MediaFile[] MediaFiles {
            get {
                return this.mediaFilesField;
            }
            set {
                this.mediaFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Manufacturer {
        
        private int manufacturerIDField;
        
        private string manufacturerNameField;
        
        private string descriptionField;
        
        private System.Nullable<bool> isDefaultField;
        
        private System.Nullable<bool> isActivedField;
        
        private System.Nullable<bool> isDeletedField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private System.Nullable<int> createdByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private System.Nullable<int> modifiedByField;
        
        private System.Nullable<System.DateTime> deletedDateField;
        
        private System.Nullable<int> deletedByField;
        
        private int companyIDField;
        
        private Company companyField;
        
        /// <remarks/>
        public int ManufacturerID {
            get {
                return this.manufacturerIDField;
            }
            set {
                this.manufacturerIDField = value;
            }
        }
        
        /// <remarks/>
        public string ManufacturerName {
            get {
                return this.manufacturerNameField;
            }
            set {
                this.manufacturerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActived {
            get {
                return this.isActivedField;
            }
            set {
                this.isActivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ModifiedBy {
            get {
                return this.modifiedByField;
            }
            set {
                this.modifiedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyProfileProperty {
        
        private int propertyIDField;
        
        private string propertyNameField;
        
        private int orderIndexField;
        
        private CompanyProfile[] companyProfilesField;
        
        /// <remarks/>
        public int PropertyID {
            get {
                return this.propertyIDField;
            }
            set {
                this.propertyIDField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
        
        /// <remarks/>
        public int OrderIndex {
            get {
                return this.orderIndexField;
            }
            set {
                this.orderIndexField = value;
            }
        }
        
        /// <remarks/>
        public CompanyProfile[] CompanyProfiles {
            get {
                return this.companyProfilesField;
            }
            set {
                this.companyProfilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyProfile {
        
        private int companyIDField;
        
        private int propertyIDField;
        
        private string propertyValueField;
        
        private Company companyField;
        
        private CompanyProfileProperty companyProfilePropertyField;
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public int PropertyID {
            get {
                return this.propertyIDField;
            }
            set {
                this.propertyIDField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyValue {
            get {
                return this.propertyValueField;
            }
            set {
                this.propertyValueField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public CompanyProfileProperty CompanyProfileProperty {
            get {
                return this.companyProfilePropertyField;
            }
            set {
                this.companyProfilePropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPermissionCompletedEventHandler(object sender, GetPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SystemPermission Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SystemPermission)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPermissionsCompletedEventHandler(object sender, GetPermissionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPermissionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPermissionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SystemPermission[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SystemPermission[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPermissionPagingCompletedEventHandler(object sender, GetPermissionPagingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPermissionPagingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPermissionPagingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PagedResultOfSystemPermission Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PagedResultOfSystemPermission)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddPermissionCompletedEventHandler(object sender, AddPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeletePermissionCompletedEventHandler(object sender, DeletePermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdatePermissionCompletedEventHandler(object sender, UpdatePermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPermissionsByUserIdCompletedEventHandler(object sender, GetPermissionsByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPermissionsByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPermissionsByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPermissionByRoleIdCompletedEventHandler(object sender, GetPermissionByRoleIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPermissionByRoleIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPermissionByRoleIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SystemPermission[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SystemPermission[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsExistPermissionCompletedEventHandler(object sender, IsExistPermissionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsExistPermissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsExistPermissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591