//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Mobile.Framework;
using Mobile.Object;

namespace Mobile.Data
{
    public partial class MobileContext : DbContext
    {
        public MobileContext(string connectionString) :
            base(new System.Data.Objects.ObjectContext(new System.Data.EntityClient.EntityConnection(Global.GetMetaData("MobileContext"),
    			new System.Data.SqlClient.SqlConnection(connectionString))), true)
        {
    		(this as IObjectContextAdapter).ObjectContext.DefaultContainerName = "MobileContext";
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advertising> Advertisings { get; set; }
        public DbSet<AdvertisingCategory> AdvertisingCategories { get; set; }
        public DbSet<Article> Articles { get; set; }
        public DbSet<ArticleCategory> ArticleCategories { get; set; }
        public DbSet<ArticleComment> ArticleComments { get; set; }
        public DbSet<Mobile.Object.Attribute> Attributes { get; set; }
        public DbSet<AttributeValue> AttributeValues { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyOnlineSupport> CompanyOnlineSupports { get; set; }
        public DbSet<CompanyProfile> CompanyProfiles { get; set; }
        public DbSet<CompanyProfileProperty> CompanyProfileProperties { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<CustomerContact> CustomerContacts { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<FriendRequest> FriendRequests { get; set; }
        public DbSet<InputType> InputTypes { get; set; }
        public DbSet<Instance> Instances { get; set; }
        public DbSet<InstanceImage> InstanceImages { get; set; }
        public DbSet<InvitationFriend> InvitationFriends { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<MediaCategory> MediaCategories { get; set; }
        public DbSet<MediaFile> MediaFiles { get; set; }
        public DbSet<MediaFileType> MediaFileTypes { get; set; }
        public DbSet<MediaImage> MediaImages { get; set; }
        public DbSet<MediaImageCategory> MediaImageCategories { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageFolder> MessageFolders { get; set; }
        public DbSet<MessageRecipient> MessageRecipients { get; set; }
        public DbSet<MessageType> MessageTypes { get; set; }
        public DbSet<Module> Modules { get; set; }
        public DbSet<OnlineSupportType> OnlineSupportTypes { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProductImage> ProductImages { get; set; }
        public DbSet<RepairVoucher> RepairVouchers { get; set; }
        public DbSet<RepairVoucherDetail> RepairVoucherDetails { get; set; }
        public DbSet<Solution> Solutions { get; set; }
        public DbSet<SolutionError> SolutionErrors { get; set; }
        public DbSet<StatisticVisitor> StatisticVisitors { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<SystemCompanyConfig> SystemCompanyConfigs { get; set; }
        public DbSet<SystemConfig> SystemConfigs { get; set; }
        public DbSet<SystemModule> SystemModules { get; set; }
        public DbSet<SystemPermission> SystemPermissions { get; set; }
        public DbSet<SystemRole> SystemRoles { get; set; }
        public DbSet<SystemRolePermission> SystemRolePermissions { get; set; }
        public DbSet<SystemRoleUser> SystemRoleUsers { get; set; }
        public DbSet<SystemUser> SystemUsers { get; set; }
        public DbSet<SystemUserPermission> SystemUserPermissions { get; set; }
        public DbSet<Warranty> Warranties { get; set; }
    }
}
